"""Quantile-based identification data access layer."""

from .reader import (
    fetch_extremes_by_type_grid_agg,
    fetch_extremes_grid_agg,
    fetch_transitions_by_type_grid_agg,
    fetch_transitions_grid_agg,
)
from .writer import upsert_extremes, upsert_transitions, upsert_labels, upsert_run_status, ensure_tables
from .schema import (
    QuantileResult,
    QuantileServiceConfig,
    QuantileBatchConfig,
    RUN_STATUS_DONE,
    RUN_STATUS_ERROR,
    CURRENT_QUANTILE_WORKFLOW_VERSION,
)
from .store import (
    ensure_quantile_tables,
    upsert_quantile_labels,
    upsert_quantile_extremes,
    upsert_quantile_abrupt_transitions,
    upsert_quantile_run_status,
    count_source_lakes_in_chunk,
    count_processed_lakes_in_chunk,
    fetch_source_hylak_ids_in_chunk,
    fetch_processed_hylak_ids_in_chunk,
    fetch_max_hylak_id,
    result_to_label_rows,
    result_to_extreme_rows,
    result_to_transition_rows,
    make_run_status_row,
    fetch_summary_cache_sources,
)

__all__ = [
    "fetch_extremes_grid_agg",
    "fetch_extremes_by_type_grid_agg",
    "fetch_transitions_grid_agg",
    "fetch_transitions_by_type_grid_agg",
    "upsert_extremes",
    "upsert_transitions",
    "upsert_labels",
    "upsert_run_status",
    "ensure_tables",
    "QuantileResult",
    "QuantileServiceConfig",
    "QuantileBatchConfig",
    "RUN_STATUS_DONE",
    "RUN_STATUS_ERROR",
    "CURRENT_QUANTILE_WORKFLOW_VERSION",
    "ensure_quantile_tables",
    "upsert_quantile_labels",
    "upsert_quantile_extremes",
    "upsert_quantile_abrupt_transitions",
    "upsert_quantile_run_status",
    "count_source_lakes_in_chunk",
    "count_processed_lakes_in_chunk",
    "fetch_processed_hylak_ids_in_chunk",
    "fetch_source_hylak_ids_in_chunk",
    "fetch_max_hylak_id",
    "result_to_label_rows",
    "result_to_extreme_rows",
    "result_to_transition_rows",
    "make_run_status_row",
    "fetch_summary_cache_sources",
]