"""Lake area data quality assessment module."""

from .classify import (
    AreaRatioConfig,
    FlatnessFilterConfig,
    LakeContext,
    PenalizedVolatilityConfig,
    OutsideRangeConfig,
    ZeroQuantileConfig,
    ZeroQuantileFilter,
    ShiftConfig,
    classify_area_anomaly,
    default_filters,
)
from .comparison import (
    enrich_comparison_df,
    summarize_comparison,
)
from .filters import (
    FLAG_AREA_RATIO,
    FLAG_FLAT,
    FLAG_MEDIAN_ZERO,
    FLAG_ZERO_QUANTILE,
    FLAG_OUTSIDE_RANGE,
    FLAG_PV,
    FLAG_SHIFT,
    FLAG_NAMES,
    AnomalyFilter,
    AnomalyFlag,
    decode_anomaly_flags,
    encode_anomaly_flags,
)
from .frozen import (
    FrozenPlateauSchedule,
    apply_frozen_plateau,
    build_frozen_plateau_schedule,
    defrozen_frame,
    filter_frozen_rows,
    first_frozen_months,
    frozen_run_indices,
    month_index_to_year_month_key,
    year_month_key_to_index,
    year_month_to_key,
)
from .interpolation import (
    CollinearSegment,
    InterpolationConfig,
    InterpolationResult,
    detect_interpolation,
    get_collinear_segments,
)
from .metrics import (
    AgreementConfig,
    classify_agreement,
    classify_outside_range,
    compute_area_range,
    compute_area_ratio,
    compute_flatness_metrics,
    compute_log2_ratio,
    compute_mean_area,
    compute_median_area,
    compute_quantile_area,
    compute_penalized_volatility,
    compute_relative_diff,
    is_anomalous,
)
from .runner import QualityRunConfig, run_quality
from .batch import QualityBatchReader, QualityBatchWriter, QualityCalculator
from .interpolation_runner import InterpolationRunConfig, run_interpolation_detect
from .maintenance_runner import (
    RecheckZeroQuantileConfig,
    RecomputePvConfig,
    run_recheck_zero_quantile,
    run_recompute_pv,
)
from .shift_labels_runner import (
    sync_shift_to_anomalies,
    upsert_shift_labels_from_parquet,
)

__all__ = [
    "AgreementConfig",
    "AnomalyFilter",
    "AnomalyFlag",
    "AreaRatioConfig",
    "FLAG_AREA_RATIO",
    "FLAG_FLAT",
    "FLAG_MEDIAN_ZERO",
    "FLAG_ZERO_QUANTILE",
    "FLAG_OUTSIDE_RANGE",
    "FLAG_PV",
    "FLAG_SHIFT",
    "FLAG_NAMES",
    "FlatnessFilterConfig",
    "FrozenPlateauSchedule",
    "InterpolationRunConfig",
    "InterpolationConfig",
    "InterpolationResult",
    "LakeContext",
    "CollinearSegment",
    "PenalizedVolatilityConfig",
    "OutsideRangeConfig",
    "QualityRunConfig",
    "QualityBatchReader",
    "QualityBatchWriter",
    "QualityCalculator",
    "RecheckZeroQuantileConfig",
    "RecomputePvConfig",
    "ZeroQuantileConfig",
    "ZeroQuantileFilter",
    "ShiftConfig",
    "apply_frozen_plateau",
    "build_frozen_plateau_schedule",
    "classify_agreement",
    "classify_area_anomaly",
    "classify_outside_range",
    "compute_area_range",
    "compute_area_ratio",
    "compute_flatness_metrics",
    "compute_log2_ratio",
    "compute_mean_area",
    "compute_median_area",
    "compute_quantile_area",
    "compute_penalized_volatility",
    "compute_relative_diff",
    "decode_anomaly_flags",
    "default_filters",
    "defrozen_frame",
    "detect_interpolation",
    "encode_anomaly_flags",
    "enrich_comparison_df",
    "filter_frozen_rows",
    "first_frozen_months",
    "frozen_run_indices",
    "get_collinear_segments",
    "is_anomalous",
    "month_index_to_year_month_key",
    "run_interpolation_detect",
    "run_quality",
    "run_recheck_zero_quantile",
    "run_recompute_pv",
    "summarize_comparison",
    "sync_shift_to_anomalies",
    "upsert_shift_labels_from_parquet",
    "year_month_key_to_index",
    "year_month_to_key",
]
