"""Algorithm result write ports (quantile, pwm, eot, hawkes, comparison, entropy)."""

from __future__ import annotations

from typing import Any, Protocol


class QuantileWritePort(Protocol):
    def ensure_quantile_tables(self) -> None: ...
    def upsert_quantile_labels(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_quantile_extremes(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_quantile_abrupt_transitions(
        self, rows: list[dict[str, Any]]
    ) -> None: ...
    def upsert_quantile_run_status(self, rows: list[dict[str, Any]]) -> None: ...
    def count_quantile_status_in_range(
        self, chunk_start: int, chunk_end: int
    ) -> int: ...
    def fetch_quantile_status_ids_in_range(
        self, chunk_start: int, chunk_end: int
    ) -> set[int]: ...


class PwmWritePort(Protocol):
    def ensure_pwm_extreme_tables(self) -> None: ...
    def upsert_pwm_extreme_thresholds(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_pwm_extreme_labels(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_pwm_extreme_extremes(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_pwm_extreme_abrupt_transitions(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_pwm_extreme_run_status(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_pwm_hawkes_run_status(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_pwm_hawkes_segments(self, rows: list[dict[str, Any]]) -> None: ...
    def count_pwm_extreme_status_in_range(
        self, chunk_start: int, chunk_end: int
    ) -> int: ...
    def fetch_pwm_extreme_status_ids_in_range(
        self, chunk_start: int, chunk_end: int
    ) -> set[int]: ...


class EotWritePort(Protocol):
    def ensure_eot_results_table(self) -> None: ...
    def upsert_eot_results(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_eot_extremes(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_eot_run_status(self, rows: list[dict[str, Any]]) -> None: ...


class PwmHawkesWritePort(Protocol):
    def ensure_pwm_hawkes_tables(self) -> None: ...
    def upsert_pwm_hawkes_results(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_pwm_hawkes_lrt(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_pwm_hawkes_transition_monthly(
        self, rows: list[dict[str, Any]]
    ) -> None: ...


class EotHawkesWritePort(Protocol):
    def ensure_eot_hawkes_tables(self) -> None: ...
    def upsert_eot_hawkes_results(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_eot_hawkes_lrt(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_eot_hawkes_transition_monthly(
        self, rows: list[dict[str, Any]]
    ) -> None: ...
    def upsert_eot_hawkes_run_status(
        self, rows: list[dict[str, Any]]
    ) -> None: ...


class HawkesWritePort(Protocol):
    """Deprecated unified port — delegates to PwmHawkesWritePort."""
    def ensure_hawkes_results_table(self) -> None: ...
    def upsert_hawkes_results(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_hawkes_lrt(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_hawkes_transition_monthly(
        self, rows: list[dict[str, Any]]
    ) -> None: ...


class ComparisonWritePort(Protocol):
    def ensure_comparison_tables(self) -> None: ...
    def upsert_comparison_run_status(
        self, rows: list[dict[str, Any]]
    ) -> None: ...
    def fetch_comparison_status_ids_in_range(
        self, chunk_start: int, chunk_end: int
    ) -> set[int]: ...


class InterpolationDetectWritePort(Protocol):
    def ensure_interpolation_detect_table(self) -> None: ...
    def upsert_interpolation_detect(self, rows: list[dict[str, Any]]) -> None: ...


class EntropyWritePort(Protocol):
    def ensure_entropy_table(self) -> None: ...
    def upsert_entropy(self, rows: list[dict[str, Any]]) -> None: ...
    def ensure_area_entropy_cv_table(self) -> None: ...
    def upsert_area_entropy_cv(self, rows: list[dict[str, Any]]) -> None: ...
