"""Quality, anomalies, and status reading ports."""

from __future__ import annotations

from typing import Any, Protocol


class QualityWritePort(Protocol):
    def ensure_area_quality_table(self) -> None: ...
    def upsert_area_quality(self, rows: list[dict[str, Any]]) -> None: ...
    def fetch_area_quality_hylak_ids_in_range(
        self, chunk_start: int, chunk_end: int
    ) -> set[int]: ...
    def count_area_quality_hylak_ids_in_range(
        self, chunk_start: int, chunk_end: int
    ) -> int: ...
    def delete_area_quality_by_ids(self, hylak_ids: list[int]) -> None: ...


class AnomaliesWritePort(Protocol):
    def ensure_area_anomalies_table(self) -> None: ...
    def upsert_area_anomalies(self, rows: list[dict[str, Any]]) -> None: ...
    def move_area_quality_to_anomalies(
        self, hylak_ids: list[int]
    ) -> int: ...
    def update_area_anomaly_flags(
        self, updates: list[tuple[int, int]]
    ) -> None: ...
    def fetch_anomaly_hylak_ids(self) -> set[int]: ...
