"""Database connection and extension checks for HydroALTAS (PostGIS + pghydro)."""

from .chunked import ChunkedLakeProcessor
from .client import DBClient, atlas_db, series_db
from .extensions import check_extensions
from .hawkes_qc import (
    fetch_eot_hawkes_coverage,
    fetch_hawkes_error_message_counts,
    fetch_hawkes_lrt,
    fetch_hawkes_lrt_summary_by_test,
    fetch_hawkes_qc_summary_by_quantile,
    fetch_hawkes_results,
    fetch_hawkes_transition_monthly,
)
from .lake import (
    ensure_area_anomalies_table,
    ensure_area_quality_table,
    ensure_entropy_table,
    ensure_eot_results_table,
    ensure_hawkes_results_table,
    upsert_eot_extremes,
    upsert_hawkes_lrt,
    upsert_hawkes_results,
    upsert_hawkes_transition_monthly,
    fetch_af_nearest_high_topo,
    fetch_area_quality_hylak_ids,
    fetch_atlas_area_chunk,
    fetch_eot_extremes_by_id,
    fetch_frozen_year_months_by_ids,
    fetch_frozen_year_months_chunk,
    fetch_lake_area,
    fetch_lake_area_by_ids,
    fetch_lake_area_chunk,
    fetch_lake_geometry_wkt_by_ids,
    fetch_linear_trend_by_ids,
    fetch_seasonal_amplitude_chunk,
    move_area_quality_to_anomalies,
    upsert_area_anomalies,
    upsert_area_quality,
    upsert_entropy,
    upsert_eot_results,
)

__all__ = [
    "ChunkedLakeProcessor",
    "DBClient",
    "atlas_db",
    "series_db",
    "check_extensions",
    "fetch_lake_area",
    "fetch_lake_area_chunk",
    "fetch_lake_area_by_ids",
    "fetch_lake_geometry_wkt_by_ids",
    "fetch_eot_extremes_by_id",
    "fetch_frozen_year_months_by_ids",
    "fetch_frozen_year_months_chunk",
    "fetch_linear_trend_by_ids",
    "fetch_af_nearest_high_topo",
    "ensure_entropy_table",
    "upsert_entropy",
    "ensure_eot_results_table",
    "ensure_hawkes_results_table",
    "upsert_eot_results",
    "upsert_eot_extremes",
    "upsert_hawkes_results",
    "upsert_hawkes_lrt",
    "upsert_hawkes_transition_monthly",
    "fetch_area_quality_hylak_ids",
    "fetch_atlas_area_chunk",
    "fetch_seasonal_amplitude_chunk",
    "move_area_quality_to_anomalies",
    "ensure_area_quality_table",
    "upsert_area_quality",
    "ensure_area_anomalies_table",
    "upsert_area_anomalies",
    "fetch_hawkes_qc_summary_by_quantile",
    "fetch_hawkes_error_message_counts",
    "fetch_hawkes_results",
    "fetch_hawkes_lrt",
    "fetch_hawkes_lrt_summary_by_test",
    "fetch_eot_hawkes_coverage",
    "fetch_hawkes_transition_monthly",
]
